### ISSUE TITLE
feat: sourcemaps for react-dom/profiling

### ISSUE THREAD

**Issue by JonasBa** [markerikson/react-prod-sourcemaps#11]
We currently do not provide sourcemaps for react-dom/profiling bundle. It would be useful if we could provide these as they might be used by a lot of folks + the current remapping behavior is slightly confusing. e.g. I only noticed this after using strict mode in our webpack build step at Sentry and have it throw and error before I noticed a webpack resolve alias for react-dom to react-dom/profiling...

@markerikson iirc you mentioned we could add these somewhat trivially? I would be happy to look into building these and checking them into the repo, wdyt?

**Comment by markerikson** [comment]
Yeah, now that I've got the branches created and updated, all I need to do is re-run the build step to generate the sourcemaps.  I can do that in the next day or so.

**Comment by JonasBa** [comment]
I would love that @markerikson! Let me open a PR for react-dom/profiling support from the CLI and the build tool as well

**Comment by markerikson** [comment]
For that matter, if you want to take a stab at doing the builds yourself, go for it.

I don't remember if I pushed up all the React version branches to the Replay fork repo, or just 18.2.

In theory, the process is:

- clone our Replay fork of React
- check out one of the sourcemap branches I made and run Yarn to install
- `RELEASE_CHANNEL=stable && yarn build`
- Compare hashes for the built artifacts to confirm they're identical to the real released artifacts
- Copy sourcemaps to this repo, add lookup entries

Also might as well add the React core package while we're at it

**Comment by markerikson** [comment]
Looking at this, and realized that we also need to change the logic around looking for filenames as well.  Right now we've got `react-dom.production` hardcoded in there.

**Comment by markerikson** [comment]
Hey, good news, I think I've got it successfully handling both multiple artifact names (`react-dom.production`, `react-dom.profiling`, `react.production`) and likely multiple versions?  haven't tested multiple versions yet, but I think the logic will deal with it now:

```
$ yarn build
vite v4.2.1 building for production...
transforming (1) index.htmlModule level directives cause errors when bundled, "use client" in "node_modules/react-redux/dist/react-redux.mjs" was ignored.
✓ 340 modules transformed.
Found possible React artifact file: ../../node_modules/react/cjs/react.production.min.js {
  importer: '',
  depth: 1,
  source: '../../node_modules/react/cjs/react.production.min.js',
  content: undefined
}
Found matching React version: 18.2.0
Loading original react sourcemap from:  C:\Projects\redux-toolkit\examples\publish-ci\vite\node_modules\@acemarke\react-prod-sourcemaps\assets\react\18.2.0\react.production.min.js.map
Skipping sourcemap entry '../../node_modules/react/cjs/react.production.js' because it is not a known React filename
Skipping sourcemap entry '../../node_modules/react/index.js' because it is not a known React filename
Skipping sourcemap entry '../../node_modules/react/cjs/react-jsx-runtime.production.min.js' because it is not a known React filename
Skipping sourcemap entry '../../node_modules/react/jsx-runtime.js' because it is not a known React filename
Skipping sourcemap entry '../../node_modules/scheduler/cjs/scheduler.production.min.js' because it is not a known React filename
Skipping sourcemap entry '../../node_modules/scheduler/index.js' because it is not a known React filename
Found possible React artifact file: ../../node_modules/react-dom/cjs/react-dom.production.min.js {
  importer: '',
  depth: 1,
  source: '../../node_modules/react-dom/cjs/react-dom.production.min.js',
  content: undefined
}
Found matching React version: 18.2.0
Loading original react-dom sourcemap from:  C:\Projects\redux-toolkit\examples\publish-ci\vite\node_modules\@acemarke\react-prod-sourcemaps\assets\react-dom\18.2.0\react-dom.production.min.js.map
Skipping sourcemap entry '../../node_modules/react-dom/cjs/react-dom.production.js' because it is not a known React filename
Skipping sourcemap entry '../../node_modules/react-dom/index.js' because it is not a known React filename
Skipping sourcemap entry '../../node_modules/react-dom/client.js' because it is not a known React filename

// snip

Found multiple React entries: [
  {
    version: '18.2.0',
    package: 'react',
    filename: 'react.production.min.js',
    contentHash: '12a71800adb60f93da6dfe5d40ebdf225101204dd51f5e7266cce243aefd6512'
  },
  {
    version: '18.2.0',
    package: 'react-dom',
    filename: 'react-dom.production.min.js',
    contentHash: '1404cd9fd1e2ee3ce79fba01957b01c83f88ccd86a3e55e6a51a871d9fe05552'
  }
]
```

![image](https://github.com/markerikson/react-prod-sourcemaps/assets/1128784/0ed2c5e6-e01b-40c9-93af-d941f5a15df6)

Will PR this shortly.

**Comment by markerikson** [comment]
Added `react` and `react-dom.profiling` for 17.0.2, 18.1, and 18.2!

https://github.com/markerikson/react-prod-sourcemaps/releases/tag/v0.2.0
